### base config ###
full_field: &FULL_FIELD
  loss: 'l2'
  lr: 1E-3
  scheduler: 'ReduceLROnPlateau'
  num_data_workers: 4
  dt: 1 # how many timesteps ahead the model will predict
  n_history: 0 #how many previous timesteps to consider
  prediction_type: 'iterative'
  prediction_length: 41 #applicable only if prediction_type == 'iterative'
  n_initial_conditions: 5 #applicable only if prediction_type == 'iterative'
  ics_type: "default"
  save_raw_forecasts: !!bool True
  save_channel: !!bool False
  masked_acc: !!bool False
  maskpath: None
  perturb: !!bool False
  add_grid: !!bool False
  N_grid_channels: 0
  gridtype: 'sinusoidal' #options 'sinusoidal' or 'linear'
  roll: !!bool False
  max_epochs: 50
  batch_size: 64

  #afno hyperparams
  num_blocks: 8
  embed_dim: 768
  nettype: 'afno'
  patch_size: 8
  width: 56
  modes: 32
  #options default, residual
  target: 'default' 
  in_channels: [0,1]
  out_channels: [0,1] #must be same as in_channels if prediction_type == 'iterative'
  normalization: 'zscore' #options zscore (minmax not supported) 
  train_data_path: '/pscratch/sd/j/jpathak/wind/train'
  valid_data_path: '/pscratch/sd/j/jpathak/wind/test'
  inf_data_path: '/pscratch/sd/j/jpathak/wind/out_of_sample' # test set path for inference
  exp_dir: '/pscratch/sd/j/jpathak/ERA5_expts_gtc/wind'
  time_means_path:   '/pscratch/sd/j/jpathak/wind/time_means.npy'
  global_means_path: '/pscratch/sd/j/jpathak/wind/global_means.npy'
  global_stds_path:  '/pscratch/sd/j/jpathak/wind/global_stds.npy'

  orography: !!bool False
  orography_path: None

  log_to_screen: !!bool True
  log_to_wandb: !!bool True
  save_checkpoint: !!bool True

  enable_nhwc: !!bool False
  optimizer_type: 'FusedAdam'
  crop_size_x: None
  crop_size_y: None

  two_step_training: !!bool False
  plot_animations: !!bool False

  add_noise: !!bool False
  noise_std: 0

  drop_path_rate: 0.
  drop_rate: 0.

  weight_decay: 0
  residual: !!bool False
  rmse_loss: !!bool False
  relative_loss: !!bool True

  decoder_scale: 1
  add_extra_years: !!bool False
  depth: 12

  interp_factor_x: 1
  interp_factor_y: 1

  project: 'highresmip'
  entity: 'climate'

afno_backbone: &backbone
  <<: *FULL_FIELD
  log_to_wandb: !!bool True
  lr: 5E-4
  batch_size: 64
  max_epochs: 150
  scheduler: 'CosineAnnealingLR'
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  orography: !!bool False
  orography_path: None 
  exp_dir: '/pscratch/sd/s/shas1693/results/era5_wind'
  train_data_path: '/pscratch/sd/s/shas1693/data/era5/train'
  valid_data_path: '/pscratch/sd/s/shas1693/data/era5/test'
  inf_data_path:   '/pscratch/sd/s/shas1693/data/era5/out_of_sample'
  time_means_path:   '/pscratch/sd/s/shas1693/data/era5/time_means.npy'
  global_means_path: '/pscratch/sd/s/shas1693/data/era5/global_means.npy'
  global_stds_path:  '/pscratch/sd/s/shas1693/data/era5/global_stds.npy'

afno_backbone_26var: &26var
  <<: *backbone
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  train_data_path:   '/pscratch/sd/j/jpathak/34var/train'
  valid_data_path:   '/pscratch/sd/j/jpathak/34var/test'
  inf_data_path:     '/pscratch/sd/j/jpathak/34var/out_of_sample'
  time_means_path:   '/pscratch/sd/j/jpathak/34var/stats/time_means.npy'
  global_means_path: '/pscratch/sd/j/jpathak/34var/stats/global_means.npy'
  global_stds_path:  '/pscratch/sd/j/jpathak/34var/stats/global_stds.npy'

afno_backbone_26var_50km:
  <<: *backbone
  interp_factor_x: 2
  interp_factor_y: 2
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  train_data_path:   '/pscratch/sd/j/jpathak/34var/train'
  valid_data_path:   '/pscratch/sd/j/jpathak/34var/test'
  inf_data_path:     '/pscratch/sd/j/jpathak/34var/out_of_sample'
  time_means_path:   '/pscratch/sd/j/jpathak/34var/new_stats/time_means.npy'
  global_means_path: '/pscratch/sd/j/jpathak/34var/new_stats/global_means.npy'
  global_stds_path:  '/pscratch/sd/j/jpathak/34var/new_stats/global_stds.npy'

afno_backbone_26var_lamb:
  <<: *26var
  optimizer_type: 'FusedLAMB'
  weight_decay: 1E-6

afno_backbone_26var_lamb_embed1536:
  <<: *26var
  optimizer_type: 'FusedLAMB'
  weight_decay: 1E-6
  embed_dim: 1536

afno_backbone_26var_lamb_rmse:
  <<: *26var
  optimizer_type: 'FusedLAMB'
  weight_decay: 1E-6
  rmse_loss: !!bool True

afno_backbone_26var_lamb_res:
  <<: *26var
  optimizer_type: 'FusedLAMB'
  weight_decay: 1E-6
  residual: !!bool True

afno_backbone_26var_finetune: 
  <<: *26var
  lr: 1E-4
  batch_size: 64
  log_to_wandb: !!bool True
  max_epochs: 50
  pretrained: !!bool True
  two_step_training: !!bool True
  prediction_length: 41 #applicable only if prediction_type == 'iterative'
  pretrained_ckpt_path: '/pscratch/sd/s/shas1693/results/era5_wind/afno_backbone_26var/2/training_checkpoints/best_ckpt.tar'

afno_backbone_26var_lamb_finetune: 
  <<: *26var
  batch_size: 64
  optimizer_type: 'FusedLAMB'
  weight_decay: 1E-6
  lr: 1E-4
  log_to_wandb: !!bool True
  max_epochs: 50
  pretrained: !!bool True
  two_step_training: !!bool True
  prediction_length: 41 #applicable only if prediction_type == 'iterative'
  pretrained_ckpt_path: '/pscratch/sd/s/shas1693/results/era5_wind/afno_backbone_26var_lamb/0/training_checkpoints/best_ckpt.tar'

afno_backbone_26var_dt4: &26var_dt4
  <<: *backbone
  dt: 4 # how many timesteps ahead the model will predict
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  train_data_path:   '/pscratch/sd/j/jpathak/34var/train'
  valid_data_path:   '/pscratch/sd/j/jpathak/34var/test'
  inf_data_path:     '/pscratch/sd/j/jpathak/34var/out_of_sample'
  time_means_path:   '/pscratch/sd/j/jpathak/34var/stats/time_means.npy'
  global_means_path: '/pscratch/sd/j/jpathak/34var/stats/global_means.npy'
  global_stds_path:  '/pscratch/sd/j/jpathak/34var/stats/global_stds.npy'

afno_backbone_26var_lamb_embed1536_dpr05_depth24_twoyears_dt4: 
  <<: *26var_dt4
  optimizer_type: 'FusedLAMB'
  weight_decay: 1E-6
  embed_dim: 1536
  drop_path_rate: 0.5
  depth: 24
  add_extra_years: !!bool True

afno_backbone_26var_lamb_embed1536_dpr03_dt4_newstats: 
  <<: *26var_dt4
  optimizer_type: 'FusedLAMB'
  weight_decay: 1E-6
  embed_dim: 1536
  drop_path_rate: 0.3
  time_means_path:   '/pscratch/sd/j/jpathak/34var/new_stats/time_means.npy'
  global_means_path: '/pscratch/sd/j/jpathak/34var/new_stats/global_means.npy'
  global_stds_path:  '/pscratch/sd/j/jpathak/34var/new_stats/global_stds.npy'

check:
  <<: *backbone
  batch_size: 4
  log_to_wandb: !!bool False

afno_backbone_orography: &backbone_orography 
  <<: *backbone
  orography: !!bool True
  orography_path: '/pscratch/sd/s/shas1693/data/era5/static/orography.h5'

afno_backbone_finetune: 
  <<: *backbone
  lr: 1E-4
  batch_size: 64
  log_to_wandb: !!bool True
  max_epochs: 50
  pretrained: !!bool True
  two_step_training: !!bool True
  prediction_length: 361 #applicable only if prediction_type == 'iterative'
  pretrained_ckpt_path: '/pscratch/sd/s/shas1693/results/era5_wind/afno_backbone/dfs/training_checkpoints/best_ckpt.tar'
#  train_data_path: '/global/cfs/cdirs/m4134/gsharing/data/FCN_ERA5_data_v0/train'
#  valid_data_path: '/global/cfs/cdirs/m4134/gsharing/data/FCN_ERA5_data_v0/test'
#  inf_data_path:   '/global/cfs/cdirs/m4134/gsharing/data/FCN_ERA5_data_v0/out_of_sample'
#  time_means_path:   '/global/cfs/cdirs/m4134/gsharing/additional/stats_v0/time_means.npy'
#  global_means_path: '/global/cfs/cdirs/m4134/gsharing/additional/stats_v0/global_means.npy'
#  global_stds_path:  '/global/cfs/cdirs/m4134/gsharing/additional/stats_v0/global_stds.npy'

perturbations:
  <<: *backbone
  lr: 1E-4
  batch_size: 64
  max_epochs: 50
  pretrained: !!bool True
  two_step_training: !!bool True
  pretrained_ckpt_path: '/pscratch/sd/j/jpathak/ERA5_expts_gtc/wind/afno_20ch_bs_64_lr5em4_blk_8_patch_8_cosine_sched/1/training_checkpoints/best_ckpt.tar'
  prediction_length: 24
  ics_type: "datetime"
  n_perturbations: 100 
  save_channel: !bool True
  save_idx: 4
  save_raw_forecasts: !!bool False
  date_strings: ["2018-01-01 00:00:00"] 
  inference_file_tag: " "
  valid_data_path: "/pscratch/sd/j/jpathak/ "
  perturb: !!bool True
  n_level: 0.3

### PRECIP ###
precip: &precip
  <<: *backbone
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  out_channels: [0]
  nettype: 'afno'
  nettype_wind: 'afno'
  log_to_wandb: !!bool True
  lr: 2.5E-4
  batch_size: 64
  max_epochs: 25
  precip: '/pscratch/sd/p/pharring/ERA5/precip/total_precipitation'
  time_means_path_tp: '/pscratch/sd/p/pharring/ERA5/precip/total_precipitation/time_means.npy'
  model_wind_path: '/pscratch/sd/s/shas1693/results/era5_wind/afno_backbone_finetune/0/training_checkpoints/best_ckpt.tar'
  precip_eps: !!float 1e-5

precip_inf:
  <<: *precip
  precip: '/global/cfs/cdirs/m4134/gsharing/data/FCN_ERA5_data_v0/precip/'
  time_means_path_tp: '/global/cfs/cdirs/m4134/gsharing/additional/stats_v0/precip/time_means.npy'
  model_wind_path: '/global/cfs/cdirs/m4134/gsharing/model_weights/FCN_weights_v0/backbone.ckpt'
  train_data_path: '/global/cfs/cdirs/m4134/gsharing/data/FCN_ERA5_data_v0/train'
  valid_data_path: '/global/cfs/cdirs/m4134/gsharing/data/FCN_ERA5_data_v0/test'
  inf_data_path: '/global/cfs/cdirs/m4134/gsharing/data/FCN_ERA5_data_v0/out_of_sample' # test set path for inference
  min_path: '/global/cfs/cdirs/m4134/pscratch/precip/total_precipitation/mins.npy' # unused and not the right file, but avoids error
  max_path: '/global/cfs/cdirs/m4134/pscratch/precip/total_precipitation/maxs.npy' # unused and not the right file, but avoids error
  time_means_path:   '/global/cfs/cdirs/m4134/gsharing/additional/stats_v0/time_means.npy'
  global_means_path: '/global/cfs/cdirs/m4134/gsharing/additional/stats_v0/global_means.npy'
  global_stds_path:  '/global/cfs/cdirs/m4134/gsharing/additional/stats_v0/global_stds.npy'
  prediction_length: 10 #applicable only if prediction_type == 'iterative'
