
# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sfno_73ch_cos_zenith: &SFNO_73CH_COS_ZENITH

    N_in_channels: 74
    N_out_channels: 73
    N_target_channels: 73
    activation_function: gelu
    add_grid: false
    add_landmask: false
    add_noise: false
    add_orography: false
    add_zenith: true
    amp_mode: none
    batch_size: 1
    channel_names: None # Read from json
    channel_weights: "auto"
    checkpointing: false
    complex_activation: real
    crop_size_x: None
    crop_size_y: None
    cuda_graph_mode: None
    data_loader_config: "pytorch"
    data_num_shards: 64
    disable_ddp: false
    dt: 1
    embed_dim: 384
    enable_benchy: false
    enable_nhwc: false
    enable_synthetic_data: false
    epsilon_factor: 0
    exp_dir: ./runs
    filter_type: linear
    finetune: false
    global_batch_size: 64
    global_means_path: /data/stats/global_means.npy
    global_stds_path: /data/stats/global_stds.npy
    grid_num_frequencies: 64
    gridtype: sinusoidal
    h_parallel_size: 1
    hard_thresholding_fraction: 1.0
    ics_type: specify_number
    ifs_acc_path: /data/ifs
    img_crop_offset_x: 0
    img_crop_offset_y: 0
    img_crop_shape_x: 721
    img_crop_shape_y: 1440
    img_local_offset_x: 0
    img_local_offset_y: 0
    img_local_shape_x: 721
    img_local_shape_y: 1440
    img_shape_x: 721
    img_shape_y: 1440
    in_channels: None # Read from json
    inf_data_path: /data/out_of_sample
    io_grid:
    - 1
    - 1
    - 1
    io_rank:
    - 0
    - 0
    - 0
    jit_mode: none
    landmask_path: /invariants/e5.oper.invariant.128_172_lsm.ll025sc.1979010100_1979010100.nc
    log_to_screen: true
    log_to_wandb: true
    log_video: 0
    loss: geometric l2
    lr: 0.001
    lr_warmup_steps: 0
    masked_acc: false
    maskpath: null
    matmul_parallel_size: 1
    max_epochs: 60
    max_path: /data/stats/maxs.npy
    metadata_json_path: ./config/data.json
    min_path: /data/stats/mins.npy
    mlp_mode: serial
    mlp_ratio: 2
    model_parallel_names:
    - h
    - w
    - matmul
    model_parallel_size: 1
    model_parallel_sizes:
    - 1
    - 1
    - 1
    multigrid_mode: none
    multistep_count: 1
    n_eval_samples: 256
    n_future: 0
    n_history: 0
    n_initial_conditions: 5
    nettype: sfno
    noise_std: 0.0
    normalization: zscore
    normalization_layer: instance_norm
    num_blocks: 8
    num_data_workers: 4
    num_layers: 8
    num_visualization_workers: 2
    operator_type: dhconv
    optimizer_beta1: 0.9
    optimizer_beta2: 0.95
    optimizer_max_grad_norm: 32
    optimizer_type: FusedAdam
    orography_path: /invariants/e5.oper.invariant.128_129_z.ll025sc.1979010100_1979010100.nc
    out_channels: None # Read from json
    parameters_reduction_buffer_count: 1
    pos_embed: 'none' # 'none', 'direct' or 'frequency'. For resoltuion invariance, use add_grid instead or use 'frequency
    prediction_length: 35
    prediction_type: iterative
    print_timings_frequency: 10
    resuming: true
    roll: false
    scale_factor: 6
    scheduler: CosineAnnealingLR
    scheduler_T_max: 60
    separable: false
    spectral_transform: sht
    split_data_channels: false
    time_means_path: /data/stats/time_means.npy
    train_data_path: /data/train
    use_mlp: true
    valid_autoreg_steps: 20
    valid_data_path: /data/test
    verbose: false
    w_parallel_size: 1
    weight_decay: 0.0
    wind_channels:
    - 0
    - 1
    - 2
    - 3
    - 8
    - 21
    - 9
    - 22
    - 10
    - 23
    - 11
    - 24
    - 12
    - 25
    - 13
    - 26
    - 14
    - 27
    - 15
    - 28
    - 16
    - 29
    - 17
    - 30
    - 18
    - 31
    - 19
    - 32
    - 20
    - 33
    wandb_name: None # If None, config will be used but you can override it here
    wandb_group: None # If None, will be 'era5_wind' + config, but you can override it here
    wandb_project: "Modulus-Launch"
    wandb_entity: "Modulus"
    wireup_info: mpi
    wireup_store: tcp
    world_size: 64

sfno_73ch: &SFNO_73CH
    <<: *SFNO_73CH_COS_ZENITH
    N_in_channels: 73
    data_loader_config: "dali"
    batch_size: 64
    world_size: 64
    loss_type: 'geo'
    img_size: [720, 1440]
    in_channels: [0, 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]
    out_channels: [0, 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]
    global_means_path: /pscratch/sd/p/pharring/73var-6hourly/staging/stats/global_means.npy
    global_stds_path: /pscratch/sd/p/pharring/73var-6hourly/staging/stats/global_stds.npy
    ifs_acc_path: /ifs
    inf_data_path: /pscratch/sd/p/pharring/73var-6hourly/staging/out_of_sample
    landmask_path: /invariants/e5.oper.invariant.128_172_lsm.ll025sc.1979010100_1979010100.nc
    orography_path: /invariants/e5.oper.invariant.128_129_z.ll025sc.1979010100_1979010100.nc
    time_means_path: /pscratch/sd/p/pharring/73var-6hourly/staging/stats/time_means.npy
    train_data_path: /pscratch/sd/p/pharring/73var-6hourly/staging/train
    valid_autoreg_steps: 1
    valid_data_path: /pscratch/sd/p/pharring/73var-6hourly/staging/test
    exp_dir: '/pscratch/sd/s/shas1693/results/sfno'
    project: "ERA5_sfno"
    entity: "weatherbenching"
    log_to_wandb: true
    wireup_info: env
    wireup_store: tcp
    optimizer_type: adam
    save_checkpoint: true
    add_zenith: true
    max_epochs: 60
    scheduler_T_max: 60
    scale_factor: 6
    drop_rate: 0
    drop_path_rate: 0

sfno_73ch_e768:
    <<: *SFNO_73CH
    embed_dim: 768
    resuming: false

sfno_73ch_cos_zenith_inference:
    <<: *SFNO_73CH_COS_ZENITH
    pretrained_checkpoint_path: './runs/sfno_73ch_cos_zenith/01/training_checkpoints/best_ckpt_mp0.tar'

sfno_73ch_cos_zenith_ensemble:
    <<: *SFNO_73CH_COS_ZENITH
    ensemble_autoreg_steps: 5
    ensemble_members: 2
    ifs_acc_path: None
    noise_amplitude: 0.02
    pretrained_checkpoint_path: './runs/sfno_73ch_cos_zenith/01/training_checkpoints/best_ckpt_mp0.tar'

sfno_73ch_2step:
    <<: *SFNO_73CH
    pretrained_checkpoint_path: '/pscratch/sd/s/shas1693/results/sfno/sfno_73ch/0/training_checkpoints/ckpt_mp0.tar'
    max_epochs: 20
    scheduler_T_max: 20
    lr: 1E-4
    finetune: !!bool True
