### base config ###
swin: &SWIN
  #swin hyperparams
  nettype: 'swin'
  embed_dim: 768
  depth: 24
  lr: 1E-3
  patch_size: 4
  window_ratio: 80
  num_heads: 8
  batch_size: 64
  drop_path_rate: 0.1
  full_pos_embed: True
  mlp_ratio: 4
  activation_ckpt: false

  # general
  log_to_screen: True
  log_to_wandb:  True
  save_checkpoint: True
  project: 'ERA5_precip'
  entity: 'flowgan'

  # optimizer and other params
  optimizer_type: 'FusedAdam'
  scheduler: 'CosineAnnealingLR'
  max_epochs: 150
  lr: 1E-3
  batch_size: 64
  num_data_workers: 8
  n_future: 0 # for many future time steps
  dt: 1 # time step
  add_zenith: False
  batch_size: 64

  # data
  img_size: [720, 1440]
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
  train_data_path:   '/pscratch/sd/j/jpathak/34var/train'
  valid_data_path:   '/pscratch/sd/j/jpathak/34var/test'
  inf_data_path:     '/pscratch/sd/j/jpathak/34var/out_of_sample'
  time_means_path:   '/pscratch/sd/j/jpathak/34var/stats/time_means.npy'
  global_means_path: '/pscratch/sd/j/jpathak/34var/stats/global_means.npy'
  global_stds_path:  '/pscratch/sd/j/jpathak/34var/stats/global_stds.npy'
  exp_dir: '/pscratch/sd/s/shas1693/results/swin'


swin_73var: &73var
  <<: *swin
  batch_size: 64
  in_channels: [0, 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]
  out_channels: [0, 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]
  train_data_path:   '/pscratch/sd/p/pharring/73var-6hourly/staging/train'
  valid_data_path:   '/pscratch/sd/p/pharring/73var-6hourly/staging/test'
  inf_data_path:     '/pscratch/sd/p/pharring/73var-6hourly/staging/out_of_sample'
  time_means_path:   '/pscratch/sd/p/pharring/73var-6hourly/staging/stats/time_means.npy'
  global_means_path: '/pscratch/sd/p/pharring/73var-6hourly/staging/stats/global_means.npy'
  global_stds_path:  '/pscratch/sd/p/pharring/73var-6hourly/staging/stats/global_stds.npy'
  add_zenith: False
  channel_names:
    - u10m
    - v10m
    - u100m
    - v100m
    - t2m
    - sp
    - msl
    - tcwv
    - u50
    - u100
    - u150
    - u200
    - u250
    - u300
    - u400
    - u500
    - u600
    - u700
    - u850
    - u925
    - u1000
    - v50
    - v100
    - v150
    - v200
    - v250
    - v300
    - v400
    - v500
    - v600
    - v700
    - v850
    - v925
    - v1000
    - z50
    - z100
    - z150
    - z200
    - z250
    - z300
    - z400
    - z500
    - z600
    - z700
    - z850
    - z925
    - z1000
    - t50
    - t100
    - t150
    - t200
    - t250
    - t300
    - t400
    - t500
    - t600
    - t700
    - t850
    - t925
    - t1000
    - r50
    - r100
    - r150
    - r200
    - r250
    - r300
    - r400
    - r500
    - r600
    - r700
    - r850
    - r925
    - r1000

